checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            - command: ./vendor/bin/phpunit --verbose --coverage-text
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run